In [12]:
import pandas as pd

In [13]:
leavetype = 'CK'
lable = 1
# filename = ['H:/BYK/Spectra/',fold, '/averspectra- ', str(H1), '-', str(H2), '.csv']  #这种结果是list
filename = 'F:/数据处理/混合样本/' + leavetype + 'avg' + '.csv'
# filename = 'H:/BYK/Spectra/02/averspectra-1-3.csv'
df = pd.read_csv(filename,header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,340,341,342,343,344,345,346,347,348,349
0,0.091266,0.092301,0.094150,0.096756,0.10002,0.10384,0.10802,0.11241,0.11684,0.12133,...,0.54266,0.54233,0.54205,0.54167,0.54134,0.54103,0.54071,0.54043,0.54020,0.53990
1,0.099854,0.100880,0.102770,0.105440,0.10884,0.11281,0.11717,0.12174,0.12636,0.13106,...,0.60458,0.60425,0.60387,0.60354,0.60334,0.60321,0.60303,0.60296,0.60302,0.60283
2,0.090740,0.092014,0.094263,0.097376,0.10127,0.10576,0.11063,0.11572,0.12085,0.12602,...,0.57717,0.57691,0.57660,0.57638,0.57607,0.57577,0.57552,0.57528,0.57493,0.57467
3,0.147280,0.149390,0.153000,0.157930,0.16400,0.17094,0.17843,0.18618,0.19399,0.20169,...,0.57904,0.57865,0.57817,0.57768,0.57722,0.57672,0.57623,0.57578,0.57532,0.57482
4,0.103780,0.105250,0.107860,0.111510,0.11611,0.12143,0.12724,0.13329,0.13939,0.14554,...,0.55946,0.55906,0.55864,0.55827,0.55808,0.55795,0.55790,0.55786,0.55791,0.55780

In [17]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,340,341,342,343,344,345,346,347,348,349
205,0.074882,0.075527,0.076739,0.078474,0.08070,0.083323,0.086221,0.089271,0.092366,0.095549,...,0.48356,0.48334,0.48311,0.48293,0.48273,0.48241,0.48213,0.48186,0.48173,0.48149
206,0.110540,0.112110,0.114890,0.118740,0.12357,0.129130,0.135180,0.141460,0.147780,0.154130,...,0.50551,0.50538,0.50539,0.50529,0.50524,0.50516,0.50522,0.50521,0.50515,0.50511
207,0.146830,0.149000,0.152650,0.157680,0.16385,0.170940,0.178630,0.186600,0.194580,0.202580,...,0.52212,0.52175,0.52139,0.52104,0.52071,0.52040,0.52016,0.51992,0.51973,0.51955
208,0.104130,0.105400,0.107690,0.110900,0.11497,0.119700,0.124890,0.130330,0.135830,0.141410,...,0.55180,0.55154,0.55128,0.55104,0.55076,0.55043,0.55016,0.54992,0.54970,0.54947
209,0.106540,0.108180,0.111110,0.115180,0.12028,0.126160,0.132550,0.139200,0.145870,0.152580,...,0.57047,0.57013,0.56993,0.56967,0.56945,0.56922,0.56916,0.56899,0.56893,0.56885

In [18]:
df.shape[0]  ## WKB实际上有243行，第一行缺失，另外还有缺失不知道在哪里

210

In [27]:
end = df.index.max() + 1

In [25]:
# for i in range(210):
#     print(i)

In [30]:
df['Label'] = [1 for _ in range(end) ]
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,341,342,343,344,345,346,347,348,349,Label
205,0.074882,0.075527,0.076739,0.078474,0.08070,0.083323,0.086221,0.089271,0.092366,0.095549,...,0.48334,0.48311,0.48293,0.48273,0.48241,0.48213,0.48186,0.48173,0.48149,1
206,0.110540,0.112110,0.114890,0.118740,0.12357,0.129130,0.135180,0.141460,0.147780,0.154130,...,0.50538,0.50539,0.50529,0.50524,0.50516,0.50522,0.50521,0.50515,0.50511,1
207,0.146830,0.149000,0.152650,0.157680,0.16385,0.170940,0.178630,0.186600,0.194580,0.202580,...,0.52175,0.52139,0.52104,0.52071,0.52040,0.52016,0.51992,0.51973,0.51955,1
208,0.104130,0.105400,0.107690,0.110900,0.11497,0.119700,0.124890,0.130330,0.135830,0.141410,...,0.55154,0.55128,0.55104,0.55076,0.55043,0.55016,0.54992,0.54970,0.54947,1
209,0.106540,0.108180,0.111110,0.115180,0.12028,0.126160,0.132550,0.139200,0.145870,0.152580,...,0.57013,0.56993,0.56967,0.56945,0.56922,0.56916,0.56899,0.56893,0.56885,1